/**
 * Every auditable action. Shared so the admin audit viewer can filter and label them; the backend
 * model validates against the same list.
 */
export const AUDIT_ACTIONS = [
  'USER_REGISTERED',
  'USER_CREATED',
  'USER_INVITED',
  'INVITE_ACCEPTED',
  'USER_STATUS_CHANGED',
  'EMAIL_VERIFIED',
  'PASSWORD_CHANGED',
  'PASSWORD_RESET',
  'SESSIONS_REVOKED',
  'REFRESH_TOKEN_REUSE_DETECTED',
  'ACCOUNT_UPDATED',
  'DONOR_PROFILE_UPDATED',
  'DONOR_VERIFICATION_CHANGED',
  'DONOR_BLOOD_GROUP_CONFIRMED',
  'HOSPITAL_PROFILE_UPDATED',
  'HOSPITAL_VERIFICATION_CHANGED',
  'BLOOD_BANK_CREATED',
  'BLOOD_BANK_UPDATED',
  'DONATION_RECORDED',
  'DONATION_TESTING_STARTED',
  'DONATION_TEST_RESULT_RECORDED',
  'BLOOD_UNIT_STATUS_CHANGED',
  'WORKFLOW_OVERRIDE',
  'REQUEST_CREATED',
  'REQUEST_UPDATED',
  'REQUEST_ESCALATED',
  'REQUEST_REVIEWED',
  'REQUEST_CANCELLED',
  'REQUEST_STATUS_CHANGED',
  'UNITS_RESERVED',
  'ALLOCATION_RELEASED',
  'ALLOCATION_ISSUED',
  'REQUEST_RECEIPT_CONFIRMED',
  'DONOR_OUTREACH_STARTED',
  'DONOR_OUTREACH_RESPONDED',
  'SETTINGS_UPDATED',
  'ACCOUNT_LOCKED',
  'ACCOUNT_DELETED',
  'DONOR_AVAILABILITY_CHANGED',
  'DONOR_CONTACT_PREFERENCES_CHANGED',
] as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const AUDIT_ENTITY_TYPES = [
  'User',
  'DonorProfile',
  'Hospital',
  'BloodBank',
  'Donation',
  'BloodUnit',
  'BloodRequest',
  'Allocation',
  'DonorOutreach',
  'SystemSetting',
] as const;
export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[number];

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  USER_REGISTERED: 'Account registered',
  USER_CREATED: 'Account created',
  USER_INVITED: 'Staff member invited',
  INVITE_ACCEPTED: 'Invitation accepted',
  USER_STATUS_CHANGED: 'Account status changed',
  EMAIL_VERIFIED: 'Email verified',
  PASSWORD_CHANGED: 'Password changed',
  PASSWORD_RESET: 'Password reset',
  SESSIONS_REVOKED: 'Signed out everywhere',
  REFRESH_TOKEN_REUSE_DETECTED: 'Suspicious session reuse blocked',
  ACCOUNT_UPDATED: 'Account details updated',
  DONOR_PROFILE_UPDATED: 'Donor profile updated',
  DONOR_VERIFICATION_CHANGED: 'Donor verification changed',
  DONOR_BLOOD_GROUP_CONFIRMED: 'Blood group confirmed',
  HOSPITAL_PROFILE_UPDATED: 'Hospital profile updated',
  HOSPITAL_VERIFICATION_CHANGED: 'Hospital verification changed',
  BLOOD_BANK_CREATED: 'Blood bank created',
  BLOOD_BANK_UPDATED: 'Blood bank updated',
  DONATION_RECORDED: 'Donation recorded',
  DONATION_TESTING_STARTED: 'Testing started',
  DONATION_TEST_RESULT_RECORDED: 'Test result recorded',
  BLOOD_UNIT_STATUS_CHANGED: 'Blood unit status changed',
  WORKFLOW_OVERRIDE: 'Administrator override',
  REQUEST_CREATED: 'Blood request raised',
  REQUEST_UPDATED: 'Blood request edited',
  REQUEST_ESCALATED: 'Request urgency escalated',
  REQUEST_REVIEWED: 'Blood request reviewed',
  REQUEST_CANCELLED: 'Blood request cancelled',
  REQUEST_STATUS_CHANGED: 'Request status changed',
  UNITS_RESERVED: 'Units reserved for request',
  ALLOCATION_RELEASED: 'Reservation released',
  ALLOCATION_ISSUED: 'Unit issued to hospital',
  REQUEST_RECEIPT_CONFIRMED: 'Receipt confirmed by hospital',
  DONOR_OUTREACH_STARTED: 'Potential donors contacted',
  DONOR_OUTREACH_RESPONDED: 'Donor responded to outreach',
  SETTINGS_UPDATED: 'System settings changed',
  ACCOUNT_LOCKED: 'Sign-in locked after failed attempts',
  ACCOUNT_DELETED: 'Account deleted (anonymised)',
  DONOR_AVAILABILITY_CHANGED: 'Donor availability changed',
  DONOR_CONTACT_PREFERENCES_CHANGED: 'Donor contact preferences changed',
};
